(define (problem test1_1.pddl)
    (:domain books)
    (:objects
        book0 book1 book2 book3 book4 book5 book6 book7 book8 book9 book10 book11 book12 book13 book14 - book
    )
    (:init
        (predecessor book0 book10)
        (predecessor book1 book7)
        (predecessor book2 book9)
        (predecessor book5 book3)
        (predecessor book7 book13)
        (predecessor book14 book8)
        (predecessor book9 book10)
        (read book8)
        (read book11)
        (read book10)
        (read book3)
        (to-read book9)
        (to-read book12)
        (to-read book4)
        (to-read book7)
    )
    (:goal
    )
)
