(define (problem test2_2.pddl)
    (:domain books)
    (:objects
        book0 book1 book2 book3 book4 book5 book6 book7 book8 book9 book10 book11 book12 book13 book14 book15 book16 book17 book18 book19 - book
    )
    (:init
        (predecessor book0 book7)
        (predecessor book15 book1)
        (predecessor book11 book4)
        (predecessor book12 book5)
        (predecessor book5 book6)
        (parallel book18 book0)
        (parallel book4 book0)
        (parallel book13 book0)
        (parallel book3 book0)
        (parallel book9 book0)
        (parallel book1 book3)
        (parallel book14 book1)
        (parallel book8 book1)
        (parallel book19 book1)
        (parallel book6 book1)
        (parallel book2 book1)
        (parallel book10 book2)
        (parallel book17 book4)
        (parallel book16 book7)
    )
    (:goal
    )
)
