(define (problem test0_16)
    (:domain books)
    (:objects
        book0 book1 book2 book3 book4 book5 book6 book7 book8 book9 book10 book11 book12 book13 book14 book15 book16 book17 book18 book19 book20 book21 book22 book23 book24 book25 - book
        January February March April May June July August September October November December - month
    )
    (:init
        (= (number January) 0)
        (= (number February) 1)
        (= (number March) 2)
        (= (number April) 3)
        (= (number May) 4)
        (= (number June) 5)
        (= (number July) 6)
        (= (number August) 7)
        (= (number September) 8)
        (= (number October) 9)
        (= (number November) 10)
        (= (number December) 11)
        (predecessor book9 book1)
        (predecessor book5 book2)
        (predecessor book2 book8)
        (predecessor book6 book23)
        (predecessor book16 book7)
        (predecessor book7 book20)
        (predecessor book21 book10)
        (predecessor book19 book15)
        (predecessor book15 book24)
        (predecessor book20 book25)
        (read book1)
        (read book3)
        (read book8)
        (read book11)
        (read book14)
        (read book19)
        (read book24)
        (to-read book4)
        (to-read book5)
        (to-read book6)
        (to-read book12)
        (to-read book15)
        (to-read book17)
        (to-read book23)
    )
    (:goal (forall (?book - book) (imply (to-read ?book) (read ?book))))
)
