(define (problem test2_2.pddl)
    (:domain books)
    (:objects
        book0 book1 book2 book3 book4 book5 book6 book7 book8 book9 book10 book11 book12 book13 book14 book15 book16 book17 book18 book19 - book
    )
    (:init
        (predecessor book0 book5)
        (predecessor book2 book14)
        (predecessor book3 book18)
        (predecessor book6 book11)
        (predecessor book7 book16)
        (predecessor book8 book15)
        (predecessor book16 book10)
        (predecessor book10 book12)
        (predecessor book12 book18)
        (predecessor book17 book13)
        (read book1)
        (read book2)
        (read book6)
        (read book9)
        (read book10)
        (read book11)
        (to-read book3)
        (to-read book5)
        (to-read book7)
        (to-read book16)
        (to-read book18)
        (to-read book19)
    )
    (:goal
    )
)
