(define (problem JocDeProva-2)
    (:domain books)
    (:objects
        bookThe Final Empire bookThe Well of Ascension bookThe Hero of Ages bookThe Alloy of Law bookShadows of Self bookThe Bands of Mourning bookThe Lost Metal bookMistborn: Secret History bookThe Eleventh Metal bookAllomancer Jak bookThe Way of Kings bookWords of Radiance bookOathbringer bookRhythm of War bookDawnshard bookEdgedancer bookHorneater - book
        January February March April May June July August September October November December - month
    )
    (:init
        (= (monthnum) 0)
        (= (number_month January) 0)
        (= (number_month February) 1)
        (= (number_month March) 2)
        (= (number_month April) 3)
        (= (number_month May) 4)
        (= (number_month June) 5)
        (= (number_month July) 6)
        (= (number_month August) 7)
        (= (number_month September) 8)
        (= (number_month October) 9)
        (= (number_month November) 10)
        (= (number_month December) 11)
        (predecessor bookThe Final Empire bookThe Well of Ascension)
        (predecessor bookThe Well of Ascension bookThe Hero of Ages)
        (predecessor bookThe Hero of Ages bookMistborn: Secret History)
        (predecessor bookThe Alloy of Law bookShadows of Self)
        (predecessor bookShadows of Self bookThe Bands of Mourning)
        (predecessor bookThe Bands of Mourning bookThe Lost Metal)
        (predecessor bookThe Way of Kings bookWords of Radiance)
        (predecessor bookWords of Radiance bookOathbringer)
        (predecessor bookOathbringer bookRhythm of War)
        (read bookThe Final Empire)
        (read bookThe Alloy of Law)
        (read bookShadows of Self)
        (read bookHorneater)
        (read bookWords of Radiance)
        (to-read bookDawnshard)
        (to-read bookRhythm of War)
        (to-read bookAllomancer Jak)
        (to-read bookEdgedancer)
        (to-read bookMistborn: Secret History)
        (to-read bookThe Hero of Ages)
        (to-read bookOathbringer)
    )
    (:goal (forall (?book - book) (imply (to-read ?book) (read ?book))))
)
