(define (problem JocDeProva-01)
    (:domain books)
    (:objects
        bookTheFinalEmpire bookTheWellOfAscension bookTheHeroOfAges bookTheAlloyOfLaw bookShadowsOfSelf bookTheBandsOfMourning bookTheLostMetal bookMistbornSecretHistory bookTheEleventhMetal bookAllomancerJak bookTheWayOfKings bookWordsOfRadiance bookOathbringer bookRhythmOfWar bookDawnshard bookEdgedancer bookHorneater - book
        January February March April May June July August September October November December - month
    )
    (:init
        (= (monthnum) 0)
        (= (number_month January) 0)
        (= (number_month February) 1)
        (= (number_month March) 2)
        (= (number_month April) 3)
        (= (number_month May) 4)
        (= (number_month June) 5)
        (= (number_month July) 6)
        (= (number_month August) 7)
        (= (number_month September) 8)
        (= (number_month October) 9)
        (= (number_month November) 10)
        (= (number_month December) 11)
        (predecessor bookTheFinalEmpire bookTheWellOfAscension)
        (predecessor bookTheWellOfAscension bookTheHeroOfAges)
        (predecessor bookTheHeroOfAges bookMistbornSecretHistory)
        (predecessor bookTheAlloyOfLaw bookShadowsOfSelf)
        (predecessor bookShadowsOfSelf bookTheBandsOfMourning)
        (predecessor bookTheBandsOfMourning bookTheLostMetal)
        (predecessor bookTheWayOfKings bookWordsOfRadiance)
        (predecessor bookWordsOfRadiance bookOathbringer)
        (predecessor bookOathbringer bookRhythmOfWar)
        (read bookHorneater)
        (read bookWordsOfRadiance)
        (read bookTheAlloyOfLaw)
        (read bookTheFinalEmpire)
        (read bookShadowsOfSelf)
        (to-read bookTheWayOfKings)
        (to-read bookMistbornSecretHistory)
        (to-read bookTheBandsOfMourning)
        (to-read bookTheWellOfAscension)
        (to-read bookOathbringer)
        (to-read bookTheHeroOfAges)
        (to-read bookTheEleventhMetal)
    )
    (:goal (forall (?book - book) (imply (to-read ?book) (read ?book))))
)
