(define (problem test0_0)
    (:domain books)
    (:objects
        book0 book1 book2 book3 book4 book5 book6 book7 book8 book9 book10 book11 book12 book13 book14 book15 book16 book17 book18 book19 - book
        January February March April May June July August September October November December - month
    )
    (:init
        (= (number January) 0)
        (= (number February) 1)
        (= (number March) 2)
        (= (number April) 3)
        (= (number May) 4)
        (= (number June) 5)
        (= (number July) 6)
        (= (number August) 7)
        (= (number September) 8)
        (= (number October) 9)
        (= (number November) 10)
        (= (number December) 11)
        (predecessor book9 book1)
        (predecessor book5 book2)
        (predecessor book2 book7)
        (predecessor book3 book18)
        (predecessor book16 book6)
        (predecessor book12 book8)
        (predecessor book8 book17)
        (predecessor book10 book13)
        (predecessor book11 book19)
        (predecessor book18 book16)
        (read book2)
        (read book3)
        (read book11)
        (read book12)
        (read book13)
        (read book19)
        (to-read book0)
        (to-read book6)
        (to-read book7)
        (to-read book9)
        (to-read book10)
        (to-read book14)
    )
    (:goal (forall (?book - book) (imply (to-read ?book) (read ?book))))
)
